/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
import type * as extensions from "./extensions";
export type { extensions };
export type { ERC20 } from "./ERC20";
