/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1155Sol from "./IERC1155.sol";
export type { ierc1155Sol };
import type * as extensions from "./extensions";
export type { extensions };
export type { ERC1155 } from "./ERC1155";
export type { IERC1155Receiver } from "./IERC1155Receiver";
