/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155MasterTokenShop__factory } from "./ERC1155MasterTokenShop__factory";
export { IERC1155MasterTokenShop__factory } from "./IERC1155MasterTokenShop__factory";
