/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IzERC1155MasterTokenShop,
  IzERC1155MasterTokenShopInterface,
} from "../../../../../../../contracts/marketplace/zERC1155TokenShop/extensions/zERC1155MasterTokenShop/interfaces/IzERC1155MasterTokenShop";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "Dividend",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IERC1155Master",
        name: "ierc1155master",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "idUsedAsShares",
        type: "uint256",
      },
    ],
    name: "SnapshotTokenSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "buyTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "dividendId",
        type: "uint256",
      },
    ],
    name: "capitalOfAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dividend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentDividendId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "setShopStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCapital",
    outputs: [
      {
        internalType: "uint256",
        name: "capital",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "dividendId",
        type: "uint256",
      },
    ],
    name: "totalCapitalAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IzERC1155MasterTokenShop__factory {
  static readonly abi = _abi;
  static createInterface(): IzERC1155MasterTokenShopInterface {
    return new utils.Interface(_abi) as IzERC1155MasterTokenShopInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IzERC1155MasterTokenShop {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IzERC1155MasterTokenShop;
  }
}
