/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc20Sol from "./IERC20.sol";
export * as extensions from "./extensions";
export { ERC20__factory } from "./ERC20__factory";
