/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorLib__factory } from "./GovernorLib__factory";
export { IGovernor__factory } from "./IGovernor__factory";
