/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Lib__factory } from "./ERC1155Lib__factory";
export { IERC1155__factory } from "./IERC1155__factory";
