/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  APrivatezERC1155MasterTokenShop,
  APrivatezERC1155MasterTokenShopInterface,
} from "../../../../../../../contracts/marketplace/zERC1155TokenShop/extensions/zERC1155MasterTokenShop/secure/APrivatezERC1155MasterTokenShop";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "Dividend",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IERC1155Master",
        name: "ierc1155master",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "idUsedAsShares",
        type: "uint256",
      },
    ],
    name: "SnapshotTokenSet",
    type: "event",
  },
] as const;

export class APrivatezERC1155MasterTokenShop__factory {
  static readonly abi = _abi;
  static createInterface(): APrivatezERC1155MasterTokenShopInterface {
    return new utils.Interface(
      _abi
    ) as APrivatezERC1155MasterTokenShopInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): APrivatezERC1155MasterTokenShop {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as APrivatezERC1155MasterTokenShop;
  }
}
