/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc1155Sol from "./IERC1155.sol";
export * as extensions from "./extensions";
export { ERC1155__factory } from "./ERC1155__factory";
export { IERC1155Receiver__factory } from "./IERC1155Receiver__factory";
