/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iGovernorSol from "./IGovernor.sol";
export * as extensions from "./extensions";
export { Governor__factory } from "./Governor__factory";
