export * from "./Area";
export * from "./Avatar";
export * from "./BottomSpace";
export * from "./CardArea";
export * from "./CircleArea";
export * from "./ContentArea";
export * from "./InfoSection";
export * from "./InfoSub";
export * from "./InfoSubDetails";
export * from "./LoadingWavesArea";
export * from "./ProfileId";
export * from "./Shape";
export * from "./Social";
export * from "./TextArea";
export * as shapes from "./Shape/";
