/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155MasterTokenShop } from "./ERC1155MasterTokenShop";
export type { IERC1155MasterTokenShop } from "./IERC1155MasterTokenShop";
