/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { APrivatezPausable } from "./APrivatezPausable";
export type { IPrivatezPausable } from "./IPrivatezPausable";
export type { PrivatezPausable } from "./PrivatezPausable";
