/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Lib__factory } from "./ERC20Lib__factory";
export { IERC20__factory } from "./IERC20__factory";
