/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155IndividualUriSol from "./ERC1155IndividualUri.sol";
export type { erc1155IndividualUriSol };
