/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IzPausable,
  IzPausableInterface,
} from "../../../../../contracts/security/zPausable/interfaces/IzPausable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
] as const;

export class IzPausable__factory {
  static readonly abi = _abi;
  static createInterface(): IzPausableInterface {
    return new utils.Interface(_abi) as IzPausableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IzPausable {
    return new Contract(address, _abi, signerOrProvider) as IzPausable;
  }
}
