/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zErc1155MasterTokenShop from "./zERC1155MasterTokenShop";
export type { zErc1155MasterTokenShop };
