/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as secure from "./secure";
export type { secure };
export type { ZERC1155MasterTokenShop } from "./ZERC1155MasterTokenShop";
