export * as areas from "./Areas";
export * as buttons from "./Buttons";
export * as common from "./common";
export * as global from "./Global";
export * as layout from "./Layout";
export * from "./Button";
export * from "./Circle";
export * from "./Div";
export * from "./H1";
export * from "./Img";
export * from "./Input";
export * from "./P";
export * from "./Path";
export * from "./Areas/";
export * from "./Loaders";
